M48
; DRILL file {KiCad 8.0.6-8.0.6-0~ubuntu24.04.1} date 2024-11-06T15:02:18+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-11-06T15:02:18+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6-8.0.6-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.370
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X76.013Y-16.95
X76.013Y-24.95
T2
X39.75Y-16.5
X39.75Y-46.5
T3
X5.0Y-5.0
X5.0Y-60.0
X40.0Y-5.0
X40.0Y-60.0
X75.0Y-5.0
X75.0Y-60.0
M30
